// javascript-sdk/apps/playground-vue/src/App.vue
<script setup lang="ts">
// 1. Importa el componente y los tipos
import { ApoloPayButton, ApoloPayClient, type ClientResponse, type ClientError } from '@apolopay-sdk/vue';

// 2. Instancia el cliente de Apolo Pay
const client = new ApoloPayClient({
  publicKey: 'pk_test_VUE_456',
});

// 3. Define el proceso de pago
const processId = 'process_id_demo';

// 4. Define los manejadores de eventos
const handleSuccess = (response: ClientResponse) => {
  console.log('¡Pago recibido (Vue)!', response.message);
  alert('¡Gracias por tu compra!');
};

const handleError = (error: ClientError) => {
  console.error('Error (Vue):', error.message);
};
</script>

<template>
  <div>
    <h1>Mi Playground de Vue 💚</h1>

    <ApoloPayButton
      :client="client"
      :processId="processId"
      barrierDismissible
      @success="handleSuccess"
      @error="handleError"
    ></ApoloPayButton>
  </div>
</template>

<style scoped>
  div {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 50px;
  }
</style>

// javascript-sdk/apps/playground-svelte/src/App.svelte
<script lang="ts">
  // 1. Importa el componente, el cliente y los tipos
  import { ApoloPayButton, ApoloPayClient } from "@apolopay-sdk/svelte";

  // 2. Instancia el cliente de Apolo Pay
  const client = new ApoloPayClient({
    publicKey: "pk_test_SVELTE_789",
  });

  // 3. Define el proceso de pago
  const processId = "process_id_demo";

  // 4. Define los manejadores de eventos
  //    (Nota: 'event' es un CustomEvent, 'event.detail' tiene los datos)
  function handleSuccess(event: any) {
    console.log("¡Pago exitoso (Svelte)!", event.detail.transactionId);
    alert("Pago exitoso: " + event.detail.transactionId);
  }

  function handleError(event: any) {
    console.error("Error en el pago (Svelte):", event.detail.message);
    alert("Error: " + event.detail.message);
  }
</script>

<main>
  <h1>Mi Playground de Svelte 🧡</h1>

  <ApoloPayButton
    {client}
    {processId}
    barrierDismissible
    on:success={handleSuccess}
    on:error={handleError}
  ></ApoloPayButton>
</main>

<style>
  main {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 50px;
    font-family: Arial, sans-serif;
  }
</style>
