// javascript-sdk/packages/react/src/index.tsx
import '@payment-button-sdk/ui';
import React, { useRef, useEffect } from 'react';

// 2. Importa los tipos para las props
import type { Locale, PaymentResponse } from '@payment-button-sdk/ui';

// 3. Re-exporta los tipos de 'core' para el usuario final
//    (Nota: @core es una dependencia de @ui, que es una dependencia nuestra)
export * from '@payment-button-sdk/ui';

// 3. Define las props "tipo React" (onSuccess, publicKey)
type PaymentButtonProps = {
  publicKey: string;
  amount: number;
  email: string;
  productTitle?: string;
  lang?: Locale;
  barrierDismissible?: boolean;
  children?: React.ReactNode;
  disabled?: boolean;
  loading?: boolean;
  label?: string;
  onSuccess?: (response: PaymentResponse) => void;
  onError?: (error: any) => void;
};

// 4. El componente de React ahora es un "ADAPTADOR"
export const PaymentButton: React.FC<PaymentButtonProps> = ({
  publicKey,
  amount,
  email,
  productTitle,
  lang,
  barrierDismissible,
  children,
  disabled,
  loading,
  label,
  onSuccess,
  onError,
}) => {
  const ref = useRef<HTMLElement>(null);

  // 5. Esconde la "fricción" de los eventos aquí
  useEffect(() => {
    const node = ref.current;
    if (!node) return;

    // Escucha el evento del Web Component y lo "traduce" al prop de React
    const handleSuccess = (event: Event) => {
      onSuccess?.((event as CustomEvent).detail);
    };
    const handleError = (event: Event) => {
      onError?.((event as CustomEvent).detail);
    };

    node.addEventListener('success', handleSuccess);
    node.addEventListener('error', handleError);

    return () => {
      node.removeEventListener('success', handleSuccess);
      node.removeEventListener('error', handleError);
    };
  }, [onSuccess, onError]);

  // 6. Renderiza el Web Component, pasando props de React (camelCase)
  //    a atributos HTML (kebab-case)
  return React.createElement(
    'payment-button',
    {
      ref,
      'public-key': publicKey,
      amount,
      email,
      'product-title': productTitle,
      lang,
      disabled,
      loading,
      label,
      'barrier-dismissible': barrierDismissible,
    },
    children
  );
};

// javascript-sdk/packages/vue/src/index.tsx
// 1. Importa el Web Component para registrarlo
import '@payment-button-sdk/ui';

// 2. Importa las herramientas de Vue
import { defineComponent, h, onMounted, ref } from 'vue';

// 3. Re-exporta los tipos de 'core' para el usuario final
//    (Nota: @core es una dependencia de @ui, que es una dependencia nuestra)
export * from '@payment-button-sdk/ui';

/**
 * El componente adaptador de Vue.
 * Traduce los eventos nativos del DOM a eventos de Vue.
 */
export const PaymentButton = defineComponent({
  name: 'PaymentButton',

  // 1. Define los props que acepta (camelCase)
  props: {
    publicKey: { type: String, required: true },
    amount: { type: Number, required: true },
    email: { type: String, required: true },
    productTitle: { type: String, required: false },
    lang: { type: String, required: false },
    disabled: { type: Boolean, required: false },
    loading: { type: Boolean, required: false },
    label: { type: String, required: false },
    barrierDismissible: { type: Boolean, required: false },
  },

  // 2. Define los eventos que emite (onSuccess -> @success)
  emits: ['success', 'error'],

  setup(props, { emit, slots }) {
    // 3. Crea una ref para el elemento del DOM
    const buttonRef = ref<HTMLElement | null>(null);

    // 4. Esconde la "fricción" de los eventos en onMounted
    onMounted(() => {
      const node = buttonRef.value;
      if (!node) return;

      // Escucha el evento del Web Component y lo "traduce" a un evento de Vue
      const handleSuccess = (event: Event) => {
        emit('success', (event as CustomEvent).detail);
      };
      const handleError = (event: Event) => {
        emit('error', (event as CustomEvent).detail);
      };

      node.addEventListener('success', handleSuccess);
      node.addEventListener('error', handleError);

      // (En Vue, los listeners se limpian automáticamente cuando el componente se desmonta)
    });

    // 5. Renderiza el Web Component
    return () => h(
      'payment-button',
      {
        // 6. Asigna la ref
        ref: buttonRef,

        // 7. Pasa los props, convirtiéndolos a kebab-case
        'public-key': props.publicKey,
        'amount': props.amount,
        'email': props.email,
        'product-title': props.productTitle,
        'lang': props.lang,
        'disabled': props.disabled,
        'loading': props.loading,
        'label': props.label,
        'barrier-dismissible': props.barrierDismissible,
      },
      // 8. Pasa el contenido del slot (ej. "Pagar Ahora")
      slots.default ? slots.default() : []
    );
  },
});
