// packages/react/src/index.tsx
import './style.css';
import React, { useState, useCallback } from 'react';
import { PaymentClient, PaymentOptions, PaymentResponse, PaymentError } from '@payment-button-sdk/core';

// Exportamos los tipos para que el usuario también los tenga
export * from '@payment-button-sdk/core';

// El Hook personalizado
export const usePaymentButton = (options: Omit<PaymentOptions, 'onSuccess' | 'onError'>) => {
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [data, setData] = useState<PaymentResponse | null>(null);
  const [error, setError] = useState<PaymentError | null>(null);

  const pay = useCallback(() => {
    setStatus('loading');

    const client = new PaymentClient({
      ...options,
      onSuccess: (response) => {
        setData(response);
        setStatus('success');
        // (Opcional) Llamar a un onSuccess del usuario
        // options.onSuccess?.(response);
      },
      onError: (error) => {
        setError(error);
        setStatus('error');
        // (Opcional) Llamar a un onError del usuario
        // options.onError?.(error);
      },
    });

    client.initiatePayment();
  }, [options]); // Depende de 'options', pero simplificado

  return { pay, status, data, error };
};

// Un componente de botón listo para usar
interface PaymentButtonProps extends Omit<PaymentOptions, 'onSuccess' | 'onError'> {
  children: React.ReactNode;
}

export const PaymentButton: React.FC<PaymentButtonProps> = ({ children, ...options }) => {
  const { pay, status } = usePaymentButton(options);

  return (
    <button onClick={pay} disabled={status === 'loading'}>
      {status === 'loading' ? 'Procesando...' : children}
    </button>
  );
};

// packages/vue/src/index.tsx
import './style.css'; // Importa el CSS para que tsup lo procese
import { ref, defineComponent, h, computed } from 'vue';

// 1. Importa la lógica y los tipos del CORE
import { PaymentClient, type PaymentOptions, type PaymentResponse, type PaymentError } from '@payment-button-sdk/core';

// 2. Re-exporta los tipos para el usuario final
export * from '@payment-button-sdk/core';

// 3. El "Composable" (equivalente al Hook de React)
export const usePaymentButton = (options: Omit<PaymentOptions, 'onSuccess' | 'onError'>) => {
  const status = ref<'idle' | 'loading' | 'success' | 'error'>('idle');
  const data = ref<PaymentResponse | null>(null);
  const error = ref<PaymentError | null>(null);

  const pay = () => {
    status.value = 'loading';
    const client = new PaymentClient({
      ...options,
      onSuccess: (response) => {
        data.value = response;
        status.value = 'success';
      },
      onError: (err) => {
        error.value = err;
        status.value = 'error';
      },
    });
    client.initiatePayment();
  };

  return { pay, status, data, error };
};

// 4. El Componente (creado con 'defineComponent' y 'h')
export const PaymentButton = defineComponent({
  name: 'PaymentButton',
  props: {
    apiKey: { type: String, required: true },
    amount: { type: Number, required: true },
    currency: { type: String, required: true },
    // ...puedes añadir más props aquí
  },
  setup(props, { slots }) {
    // Usa el composable
    const { pay, status } = usePaymentButton({
      apiKey: props.apiKey,
      amount: props.amount,
      currency: props.currency,
    });

    const isDisabled = computed(() => status.value === 'loading');

    // Renderiza el botón
    return () => h(
      'button',
      {
        class: 'payment-button-vue', // Usa la clase CSS de Vue
        onClick: pay,
        disabled: isDisabled.value,
      },
      // Texto del botón (Slot)
      status.value === 'loading' 
        ? 'Procesando...' 
        : (slots.default ? slots.default() : 'Pagar con Vue')
    );
  },
});
