// javascript-sdk/apps/playground-svelte/src/App.svelte
<script lang="ts">
  import { ApoloPayButton, ApoloPayClient } from "@apolopay-sdk/svelte";

  // --- VALORES INICIALES (OPCIONALES) ---
  const initialPublicKey = "";
  const initialPrivateKey = "";
  const initialProcessId = "";
  // --------------------------------------

  interface LogEntry {
    message: string;
    type: 'system' | 'success' | 'error' | 'info';
    time: string;
  }

  let pubKey = initialPublicKey;
  let privKey = initialPrivateKey;
  let amount = 1;
  let client: ApoloPayClient | undefined = undefined;
  let processId = initialProcessId;
  let isLoading = false;
  let status = initialProcessId ? "Botón Listo ✅" : "Esperando configuración...";
  let logs: LogEntry[] = [
    { message: "Playground iniciado...", type: 'system', time: new Date().toLocaleTimeString() }
  ];

  function addLog(message: string, type: LogEntry['type'] = 'system') {
    logs = [{ message, type, time: new Date().toLocaleTimeString() }, ...logs];
  }

  async function getProcessId(amt: number, key: string) {
    const response = await fetch("https://pb-api.apolopay.app/payment-button/process/preorder", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-secret-key": key,
      },
      body: JSON.stringify({ amount: amt }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || "Error al obtener processId");
    }

    const data = await response.json();
    return data.result.id;
  }

  async function handleUpdate() {
    if (!pubKey || !privKey || isNaN(amount)) {
      addLog("Por favor, completa todos los campos correctamente", "error");
      return;
    }

    isLoading = true;
    status = "Obteniendo processId...";
    addLog(`Iniciando configuración (Monto: ${amount})...`, "info");

    try {
      const newProcessId = await getProcessId(amount, privKey);
      addLog(`Process ID obtenido: ${newProcessId}`, "success");

      const newClient = new ApoloPayClient({ publicKey: pubKey });
      client = newClient;
      processId = newProcessId;
      status = "Botón Listo ✅";
      addLog("Botón listo para usar", "success");
    } catch (error: any) {
      console.error(error);
      addLog(`Error: ${error.message}`, "error");
      status = "Error en configuración";
    } finally {
      isLoading = false;
    }
  }

  function clearLogs() {
    logs = [];
  }
</script>

<div class="app-container">
  <aside class="sidebar">
    <div class="sidebar-header">
      <div class="logo">
        <span class="logo-accent">Apolo</span> Pay
      </div>
      <h1>Playground Svelte</h1>
    </div>

    <div class="config-section">
      <div class="input-group">
        <label for="publicKey">Public Key (pk_...)</label>
        <input 
          type="text" 
          id="publicKey" 
          placeholder="pk_..." 
          bind:value={pubKey}
        />
      </div>

      <div class="input-group">
        <label for="privateKey">Private Key (Secret Key)</label>
        <input 
          type="password" 
          id="privateKey" 
          placeholder="sk_..." 
          bind:value={privKey}
        />
        <small>Solo para uso local en este playground</small>
      </div>

      <div class="input-group">
        <label for="amount">Monto (Amount)</label>
        <input 
          type="number" 
          id="amount" 
          bind:value={amount}
          step="0.01" 
        />
      </div>

      <button 
        id="update-btn" 
        class="primary-btn" 
        on:click={handleUpdate}
        disabled={isLoading}
      >
        <span class="btn-text" class:hidden={isLoading}>Configurar Botón</span>
        <span class="loader" class:hidden={!isLoading}></span>
      </button>
    </div>

    <div class="status-panel">
      <div class="status-item">
        <span class="status-label">Estado:</span>
        <span class="status-value">{status}</span>
      </div>
      {#if processId}
        <div class="status-item">
          <span class="status-label">Process ID:</span>
          <span class="status-value code">{processId}</span>
        </div>
      {/if}
    </div>
  </aside>

  <main class="preview-area">
    <div class="preview-card">
      <div class="preview-header">
        <h2>Vista Previa</h2>
        <p>Aquí es donde aparecerá tu botón de pago configurado</p>
      </div>
      <div class="button-preview-container">
        {#if !processId || !client}
          <div class="placeholder">
            Configura las llaves para ver el botón
          </div>
        {:else}
          <ApoloPayButton
            {client}
            {processId}
            barrierDismissible
            onSuccess={(data) => addLog(`PAGO EXITOSO: ${data.message}`, "success")}
            onError={(err) => addLog(`ERROR EN PAGO: ${err.message}`, "error")}
            onExpired={(err) => addLog(`EL PAGO HA EXPIRADO: ${err.message}`, "error")}
            onDismissed={() => addLog("Pago cancelado por el usuario", "system")}
          />
        {/if}
      </div>
    </div>

    <div class="events-log">
      <div class="log-header">
        <h3>Registro de Eventos</h3>
        <button on:click={clearLogs}>Limpiar</button>
      </div>
      <div class="logs-content">
        {#each logs as log}
          <div class="log-entry {log.type}">
            [{log.time}] {log.message}
          </div>
        {/each}
      </div>
    </div>
  </main>
</div>

// javascript-sdk/apps/playground-react/src/App.tsx
import { ApoloPayClient, ApoloPayButton } from '@apolopay-sdk/react';
import { useState } from 'react';

// --- VALORES INICIALES (OPCIONALES) ---
const initialPublicKey = "";
const initialPrivateKey = "";
const initialProcessId = "";
// --------------------------------------

interface LogEntry {
  message: string;
  type: 'system' | 'success' | 'error' | 'info';
  time: string;
}

function App() {
  const [pubKey, setPubKey] = useState(initialPublicKey);
  const [privKey, setPrivKey] = useState(initialPrivateKey);
  const [amount, setAmount] = useState(1);
  const [client, setClient] = useState<ApoloPayClient | undefined>(undefined);
  const [processId, setProcessId] = useState(initialProcessId);
  const [isLoading, setIsLoading] = useState(false);
  const [status, setStatus] = useState(initialProcessId ? "Botón Listo ✅" : "Esperando configuración...");
  const [logs, setLogs] = useState<LogEntry[]>([
    { message: "Playground iniciado...", type: 'system', time: new Date().toLocaleTimeString() }
  ]);

  const addLog = (message: string, type: LogEntry['type'] = 'system') => {
    setLogs(prev => [{ message, type, time: new Date().toLocaleTimeString() }, ...prev]);
  };

  const getProcessId = async (amt: number, key: string) => {
    const response = await fetch("https://pb-api.apolopay.app/payment-button/process/preorder", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-secret-key": key,
      },
      body: JSON.stringify({ amount: amt }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.message || "Error al obtener processId");
    }

    const data = await response.json();
    return data.result.id;
  };

  const handleUpdate = async () => {
    if (!pubKey || !privKey || isNaN(amount)) {
      addLog("Por favor, completa todos los campos correctamente", "error");
      return;
    }

    setIsLoading(true);
    setStatus("Obteniendo processId...");
    addLog(`Iniciando configuración (Monto: ${amount})...`, "info");

    try {
      const newProcessId = await getProcessId(amount, privKey);
      addLog(`Process ID obtenido: ${newProcessId}`, "success");

      const newClient = new ApoloPayClient({ publicKey: pubKey });
      setClient(newClient);
      setProcessId(newProcessId);
      setStatus("Botón Listo ✅");
      addLog("Botón listo para usar", "success");
    } catch (error: any) {
      console.error(error);
      addLog(`Error: ${error.message}`, "error");
      setStatus("Error en configuración");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="app-container">
      <aside className="sidebar">
        <div className="sidebar-header">
          <div className="logo">
            <span className="logo-accent">Apolo</span> Pay
          </div>
          <h1>Playground React</h1>
        </div>

        <div className="config-section">
          <div className="input-group">
            <label htmlFor="publicKey">Public Key (pk_...)</label>
            <input 
              type="text" 
              id="publicKey" 
              placeholder="pk_..." 
              value={pubKey} 
              onChange={(e) => setPubKey(e.target.value)}
            />
          </div>

          <div className="input-group">
            <label htmlFor="privateKey">Private Key (Secret Key)</label>
            <input 
              type="password" 
              id="privateKey" 
              placeholder="sk_..." 
              value={privKey}
              onChange={(e) => setPrivKey(e.target.value)}
            />
            <small>Solo para uso local en este playground</small>
          </div>

          <div className="input-group">
            <label htmlFor="amount">Monto (Amount)</label>
            <input 
              type="number" 
              id="amount" 
              value={amount} 
              step="0.01" 
              onChange={(e) => setAmount(parseFloat(e.target.value))}
            />
          </div>

          <button 
            id="update-btn" 
            className="primary-btn" 
            onClick={handleUpdate}
            disabled={isLoading}
          >
            <span className={`btn-text ${isLoading ? 'hidden' : ''}`}>Configurar Botón</span>
            <span className={`loader ${isLoading ? '' : 'hidden'}`}></span>
          </button>
        </div>

        <div className="status-panel">
          <div className="status-item">
            <span className="status-label">Estado:</span>
            <span className="status-value">{status}</span>
          </div>
          {processId && (
            <div className="status-item">
              <span className="status-label">Process ID:</span>
              <span className="status-value code">{processId}</span>
            </div>
          )}
        </div>
      </aside>

      <main className="preview-area">
        <div className="preview-card">
          <div className="preview-header">
            <h2>Vista Previa</h2>
            <p>Aquí es donde aparecerá tu botón de pago configurado</p>
          </div>
          <div className="button-preview-container">
            {(!processId || !client) ? (
              <div className="placeholder">
                Configura las llaves para ver el botón
              </div>
            ) : (
              <ApoloPayButton
                client={client}
                processId={processId}
                barrierDismissible
                onSuccess={(e) => addLog(`PAGO EXITOSO: ${e.message}`, "success")}
                onError={(e) => addLog(`ERROR EN PAGO: ${e.message}`, "error")}
                onExpired={() => addLog("EL PAGO HA EXPIRADO", "error")}
                onDismissed={() => addLog("Pago cancelado por el usuario", "system")}
              />
            )}
          </div>
        </div>

        <div className="events-log">
          <div className="log-header">
            <h3>Registro de Eventos</h3>
            <button onClick={() => setLogs([])}>Limpiar</button>
          </div>
          <div className="logs-content">
            {logs.map((log, i) => (
              <div key={i} className={`log-entry ${log.type}`}>
                [{log.time}] {log.message}
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;
