// apps/playground-svelte/src/App.svelte
<script lang="ts">
  // 1. Importa el botón y los tipos
  import { PaymentButton, type PaymentResponse, type PaymentError } from '@payment-button-sdk/svelte';

  // 2. Manejadores de eventos
  function handleSuccess(event: CustomEvent<PaymentResponse>) {
    console.log('Pago exitoso (Svelte)!', event.detail.transactionId);
    alert('Pago exitoso: ' + event.detail.transactionId);
  }

  function handleError(event: CustomEvent<PaymentError>) {
    console.error('Error en el pago (Svelte):', event.detail.message);
    alert('Error: ' + event.detail.message);
  }
</script>

<main>
  <h1>Mi Playground de Svelte 🧡</h1>

  <PaymentButton
    apiKey="pk_test_SVELTE_789"
    amount={500}
    currency="USD"
    on:success={handleSuccess}
    on:error={handleError}
  >
    Pagar 5.00 USD
  </PaymentButton>
</main>

<style>
  main {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 50px;
    font-family: Arial, sans-serif;
  }
</style>

// javascript-sdk/apps/playground-vue/src/App.vue
<script setup lang="ts">
// 1. Importa el componente y los tipos
import { PaymentButton, type PaymentResponse } from '@payment-button-sdk/vue';

// 2. Define los manejadores de eventos
const handleSuccess = (response: PaymentResponse) => {
  console.log('¡Pago recibido (Vue)!', response.transactionId);
  alert('¡Gracias por tu compra!');
};

const handleError = (error: any) => {
  console.error('Error (Vue):', error.message);
};
</script>

<template>
  <div>
    <h1>Mi Playground de Vue 💚</h1>

    <PaymentButton
      apiKey="pk_test_VUE_456"
      :amount="2500"
      email="test@example.com"
      @success="handleSuccess"
      @error="handleError"
    ></PaymentButton>
  </div>
</template>

<style scoped>
  div {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 50px;
  }
</style>
