// javascript-sdk/packages/svelte/src/lib/ApoloPayButton.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  // 1. Importa el Web Component para registrarlo
  import "@apolopay-sdk/ui";
  import type { 
    Locale, 
    ApoloPayClient, 
    ClientResponse, 
    ClientError, 
    PartialPaymentResponseData 
  } from "@apolopay-sdk/ui";

  // 2. Define los props que el wrapper acepta
  export let client: ApoloPayClient | undefined = undefined;
  export let processId: string | undefined = undefined;
  export let productTitle: string | undefined = undefined;
  export let lang: Locale | undefined = undefined;
  export let disabled: boolean = false;
  export let loading: boolean = false;
  export let label: string | undefined = undefined;
  export let barrierDismissible: boolean = false;

  // 2.1 Callbacks (opcionales) para recibir los datos directamente
  export let onSuccess: ((res: ClientResponse) => void) | undefined = undefined;
  export let onPartialPayment: ((res: ClientResponse<PartialPaymentResponseData>) => void) | undefined = undefined;
  export let onError: ((err: ClientError) => void) | undefined = undefined;
  export let onExpired: ((err: ClientError) => void) | undefined = undefined;
  export let onDismissed: (() => void) | undefined = undefined;

  // 3. Define el despachador de eventos con tipos formales
  const dispatch = createEventDispatcher<{
    success: ClientResponse;
    partialPayment: ClientResponse<PartialPaymentResponseData>;
    error: ClientError;
    expired: ClientError;
    dismissed: void;
  }>();

  // 4. Manejadores para re-despachar eventos con sus tipos
  function handleSuccess(e: CustomEvent<ClientResponse>) {
    dispatch('success', e.detail);
    onSuccess?.(e.detail);
  }

  function handlePartialPayment(e: CustomEvent<ClientResponse<PartialPaymentResponseData>>) {
    dispatch('partialPayment', e.detail);
    onPartialPayment?.(e.detail);
  }

  function handleError(e: CustomEvent<ClientError>) {
    dispatch('error', e.detail);
    onError?.(e.detail);
  }

  function handleExpired(e: CustomEvent<ClientError>) {
    dispatch('expired', e.detail);
    onExpired?.(e.detail);
  }

  function handleDismissed() {
    dispatch('dismissed');
    onDismissed?.();
  }
</script>

<apolopay-button
  client={client}
  process-id={processId}
  product-title={productTitle}
  {lang}
  {disabled}
  {loading}
  {label}
  barrier-dismissible={barrierDismissible}
  on:success={handleSuccess}
  on:partialPayment={handlePartialPayment}
  on:error={handleError}
  on:expired={handleExpired}
  on:dismissed={handleDismissed}
>
  <slot />
</apolopay-button>

// javascript-sdk/packages/angular/src/lib/apolopay-button.component.ts
import { Component, Input, Output, EventEmitter, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import type { ClientResponse, ClientError, Locale, ApoloPayClient, PaymentResponseData, PartialPaymentResponseData } from '@apolopay-sdk/ui';

@Component({
  selector: 'apolopay-button-component',
  standalone: true,
  template: `
    <apolopay-button
      [client]="client"
      [attr.process-id]="processId"
      [label]="label"
      [lang]="lang"
      [attr.product-title]="productTitle"
      [loading]="loading"
      [disabled]="disabled"
      [attr.barrier-dismissible]="barrierDismissible ? '' : null"
      (success)="onSuccess($event)"
      (partialPayment)="onPartialPayment($event)"
      (error)="onError($event)"
      (expired)="onExpired($event)"
      (dismissed)="onDismissed()"
    >
      <ng-content></ng-content>
    </apolopay-button>
  `,
  // 4. Asegura que el wrapper se comporte como un bloque
  styles: [`
    :host { display: inline-block; }

    apolopay-button { display: block; }
  `],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ]
})
export class ApoloPayButtonComponent {
  // 5. Define los Inputs (props)
  @Input() client?: ApoloPayClient;
  @Input() processId?: string;
  @Input() productTitle?: string;
  @Input() lang?: Locale;
  @Input() label?: string;
  @Input() loading?: boolean;
  @Input() disabled?: boolean;
  @Input() barrierDismissible?: boolean;

  // 6. Define los Outputs (eventos)
  @Output() success = new EventEmitter<ClientResponse<PaymentResponseData>>();
  @Output() partialPayment = new EventEmitter<ClientResponse<PartialPaymentResponseData>>();
  @Output() error = new EventEmitter<ClientError>();
  @Output() expired = new EventEmitter<ClientError>();
  @Output() dismissed = new EventEmitter<void>();

  // 7. Traduce el CustomEvent ($event) a un EventEmitter de Angular
  onSuccess(event: Event) {
    // $event.detail contiene los datos del evento del Web Component
    this.success.emit((event as CustomEvent<ClientResponse<PaymentResponseData>>).detail);
  }

  onPartialPayment(event: Event) {
    // $event.detail contiene los datos del evento del Web Component
    this.partialPayment.emit((event as CustomEvent<ClientResponse<PartialPaymentResponseData>>).detail);
  }

  onError(event: Event) {
    this.error.emit((event as CustomEvent<ClientError>).detail);
  }

  onExpired(event: Event) {
    this.expired.emit((event as CustomEvent<ClientError>).detail);
  }

  onDismissed() {
    this.dismissed.emit();
  }
}
