// javascript-sdk/packages/svelte/src/lib/PaymentButton.svelte
<script lang="ts">
  // 1. Importa el Web Component para registrarlo
  import "@payment-button-sdk/ui";
  import type { Locale } from "@payment-button-sdk/ui";

  // 2. Define los props que el wrapper acepta
  export let publicKey: string;
  export let amount: number;
  export let metadata: Record<string, any> | undefined = undefined;
  export let productTitle: string | undefined = undefined;
  export let lang: Locale | undefined = undefined;
  export let disabled: boolean = false;
  export let loading: boolean = false;
  export let label: string | undefined = undefined;
  export let barrierDismissible: boolean = false;
</script>

<payment-button
  public-key={publicKey}
  {amount}
  {metadata}
  product-title={productTitle}
  {lang}
  {disabled}
  {loading}
  {label}
  barrier-dismissible={barrierDismissible}
  on:success
  on:error
>
  <slot />
</payment-button>

// javascript-sdk/packages/angular/src/lib/payment-button.component.ts
import { Component, Input, Output, EventEmitter, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import type { ClientResponse, ClientError, Locale } from '@payment-button-sdk/ui';

@Component({
  selector: 'apolo-payment-button',
  standalone: true,
  template: `
    <payment-button
      [attr.public-key]="publicKey"
      [amount]="amount"
      [label]="label"
      [metadata]="metadata"
      [lang]="lang"
      [attr.product-title]="productTitle"
      [loading]="loading"
      [disabled]="disabled"
      [attr.barrier-dismissible]="barrierDismissible ? '' : null"
      (success)="onSuccess($event)"
      (error)="onError($event)"
    >
      <ng-content></ng-content>
    </payment-button>
  `,
  // 4. Asegura que el wrapper se comporte como un bloque
  styles: [`
    :host { display: inline-block; }

    payment-button { display: block; }
  `],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ]
})
export class PaymentButtonComponent {
  // 5. Define los Inputs (props)
  @Input() publicKey!: string;
  @Input() amount!: number;
  @Input() metadata?: Record<string, any>;
  @Input() productTitle?: string;
  @Input() lang?: Locale;
  @Input() label?: string;
  @Input() loading?: boolean;
  @Input() disabled?: boolean;
  @Input() barrierDismissible?: boolean;

  // 6. Define los Outputs (eventos)
  @Output() success = new EventEmitter<ClientResponse>();
  @Output() error = new EventEmitter<ClientError>();

  // 7. Traduce el CustomEvent ($event) a un EventEmitter de Angular
  onSuccess(event: Event) {
    // $event.detail contiene los datos del evento del Web Component
    this.success.emit((event as CustomEvent<ClientResponse>).detail);
  }

  onError(event: Event) {
    this.error.emit((event as CustomEvent<ClientError>).detail);
  }
}
